# Generated by Django 3.2.7 on 2022-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='imageurl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
