# Generated by Django 3.2.7 on 2022-03-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='shortname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
