# Generated by Django 3.2.7 on 2022-04-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_experience_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('timespan', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('objective', models.TextField()),
                ('imageurl', models.TextField()),
            ],
        ),
    ]
