# Generated by Django 3.2.7 on 2022-04-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shortname',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
